# Generated by Django 4.0.6 on 2022-09-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('summary', models.TextField()),
                ('color', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('softDelete', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
