# Generated by Django 4.0.6 on 2022-09-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(verbose_name='current'),
        ),
        migrations.AlterField(
            model_name='product',
            name='softDelete',
            field=models.IntegerField(default=0),
        ),
    ]
