# Generated by Django 4.0.6 on 2022-09-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_alter_product_date_alter_product_softdelete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
    ]
