# Generated by Django 4.0.6 on 2022-09-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categories',
        ),
    ]
