# Generated by Django 4.0.6 on 2022-09-12 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_rename_category_product_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
    ]
