# Generated by Django 4.0.6 on 2022-09-12 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_pizza_topping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committeeName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('sem', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriptionDate', models.DateTimeField(auto_now_add=True)),
                ('committeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.committee')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.student')),
            ],
        ),
        migrations.AddField(
            model_name='committee',
            name='student',
            field=models.ManyToManyField(through='blogapp.Subscription', to='blogapp.student'),
        ),
    ]
