# Generated by Django 4.0.6 on 2022-09-12 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0007_committee_student_subscription_committee_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='committeId',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='studentId',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='pizzaTopping',
        ),
        migrations.AlterField(
            model_name='blog',
            name='personId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Committee',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
