# Generated by Django 4.0.6 on 2022-09-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_remove_subscription_committeid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='file',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
